from enum import Enum 

class ResponseSignal(Enum):
    FILE_TYPE_NOT_SUPPORTED="FILE_TYPE_NOT_SUPPORTED"
    FILE_SIZE_EXCEEDED="FILE_SIZE_EXCEEDED"
    FILE_VALIDATED_SUCCESS="FILE_VALIDATED_SUCCESS"
    FILE_INVALID_PDF="FILE_INVALID_PDF"
    FILE_INVALID_DOCX="FILE_INVALID_DOCX"
    FILE_INVALID_TXT="FILE_INVALID_TXT"